# paths - All paths are relative to this file

output_path: "data"

# Sources to be scraped: Comment out either to ignore it when running skraper.
# Defaults to Linkedin, Glassdoor and BrighterMonday.
# Linkedin scraper is WIP
sources:
# - "Linkedin"
  - "Glassdoor"
  - "BrighterMonday"

# Search keywords to be submitted during the search
keywords: "Software Developer"

delay: True

delay_range:
  min_delay: 2
  max_delay: 10
