# paths - All paths are relative to this file

output_path: "data"

# Sources to be scraped: Comment out either to ignore it when running skraper.
# Defaults to Linkedin, Glassdoor and BrighterMonday.
sources:
  # - "Linkedin"
  - "Glassdoor"
  - "BrighterMonday"

# Search keywords to be submitted during the search
keywords: "Software Developer"

delay: 2
