language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - python setup.py install
script:
  - pytest
after_success:
  - coveralls
