language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=skraper --cov=utils --cov=config
after_success:
  - coveralls
