language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
   - pip install pytest-cov
   - pip install coveralls
   - pip install coverage
script:
  - coverage run -m pytest
after_success:
   - coveralls
